smtp:
  address: localhost
  port: 1025

url_options:
  host: localhost
  port: 4000
  protocol: http

secure_session_cookie?: false

imagemagick_path: /opt/ImageMagick/bin/

admin:
  web_authn_required: false

ticketing:
  ticket_barcode_base_url: 'http://ao-imac.local:4000/tickets/'

stripe:
  enabled: false
